apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: locust-poc-
  namespace: tekton-llamastack
spec:
  taskRef:
    name: run-locust
  params:
    - name: HOST
      value: "http://llamastack-rhoai32-postgres-otel-service.llamastack.svc.cluster.local:8321"
    - name: USERS
      value: "3"
    - name: SPAWN_RATE
      value: "1"
    - name: RUN_TIME_SECONDS
      value: "30"
    - name: MCP_SERVER
      value: "http://sdg-docs-mcp-server.llamastack.svc.cluster.local:8000/sse"
    - name: MODEL
      value: "vllm-inference/llama-32-3b-instruct"
    - name: PROMPT
      value: "What is Kubernetes?"
    - name: LOAD_SHAPE
      value: "steady"
    - name: MLFLOW_URL
      value: ""
    - name: MLFLOW_EXPERIMENT
      value: "llamastack-tekton-poc"
    - name: LOCUST_IMAGE
      value: "quay.io/rh-ee-tosokin/locust-openai:v2-mlflow"
    - name: ENABLE_MLFLOW
      value: "true"  # Uses MLFLOW_TRACKING_ARN from secret
