apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: locust-spike-test-
  namespace: tekton-llamastack
spec:
  taskRef:
    name: run-locust
  params:
    - name: HOST
      value: "http://llamastack-benchmark-service.llamastack-bench.svc.cluster.local:8321"
    - name: USERS
      value: "10"
    - name: SPAWN_RATE
      value: "2"
    - name: RUN_TIME_SECONDS
      value: "60"
    - name: MCP_SERVER
      value: "http://sdg-docs-mcp-server.llamastack-bench.svc.cluster.local:8000/sse"
    - name: MODEL
      value: "vllm-inference/llama-32-3b-instruct"
    - name: PROMPT
      value: "What is Kubernetes?"
    - name: LOAD_SHAPE
      value: "spike"
    - name: EXTRA_ENV
      value: |
        SPIKE_BASELINE_USERS=3
        SPIKE_PEAK_USERS=15
        SPIKE_BASELINE_DURATION=15
        SPIKE_RAMP_DURATION=10
        SPIKE_HOLD_DURATION=30
        SPIKE_COOLDOWN_DURATION=15
    - name: LOCUST_IMAGE
      value: "quay.io/rh-ee-tosokin/locust-openai:v2-mlflow"
    - name: ENABLE_MLFLOW
      value: "true"
    - name: MLFLOW_EXPERIMENT
      value: "llamastack-tekton-shapes"
