apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack-rhoai32-postgres-otel
  namespace: llamastack
spec:
  replicas: 1
  server:
    autoscaling:
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 75
      targetMemoryUtilizationPercentage: 70
    podOverrides:
      serviceAccountName: default
      # Init container to apply the tracing patch
      initContainers:
        - name: apply-tracing-patch
          image: quay.io/opendatahub/llama-stack:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Applying tracing patch..."
              cp /patch/tracing.py /opt/app-root/lib/python3.11/site-packages/llama_stack/providers/utils/telemetry/tracing.py
              echo "Tracing patch applied successfully"
          volumeMounts:
            - name: tracing-patch
              mountPath: /patch
            - name: site-packages
              mountPath: /opt/app-root/lib/python3.11/site-packages/llama_stack/providers/utils/telemetry
      volumes:
        - name: tracing-patch
          configMap:
            name: llamastack-tracing-patch
        - name: site-packages
          emptyDir: {}
    containerSpec:
      env:
        - name: VLLM_URL
          value: "http://llama-32-3b-instruct-predictor.bench.svc.cluster.local:80/v1"
        - name: INFERENCE_MODEL
          value: "llama-32-3b-instruct"
        - name: VLLM_TLS_VERIFY
          value: "false"
        - name: FMS_ORCHESTRATOR_URL
          value: "http://localhost:1234"
        - name: ENABLE_SENTENCE_TRANSFORMERS
          value: "true"
        - name: EMBEDDING_PROVIDER
          value: "sentence-transformers"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.llamastack.svc.cluster.local:4318"
        - name: OTEL_SERVICE_NAME
          value: "llamastack"
        - name: POSTGRES_HOST
          value: "postgres.llamastack.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
      name: llama-stack
      port: 8321
      # Volume mount for the patched telemetry module
      volumeMounts:
        - name: site-packages
          mountPath: /opt/app-root/lib/python3.11/site-packages/llama_stack/providers/utils/telemetry
    distribution:
      # Use whatever LlamaStack image you want to test
      image: quay.io/opendatahub/llama-stack:latest
    storage:
      size: 20Gi
      mountPath: /opt/app-root/src/.llama/distributions/rh
