apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack-rhoai32-ext-embedding
  namespace: llamastack
spec:
  replicas: 1
  server:
    autoscaling:
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 75
      targetMemoryUtilizationPercentage: 70
    podOverrides:
      serviceAccountName: default
    containerSpec:
      env:
        - name: VLLM_URL
          value: "http://llama-32-3b-instruct-predictor.bench.svc.cluster.local:80/v1"
        - name: INFERENCE_MODEL
          value: "llama-32-3b-instruct"
        - name: VLLM_TLS_VERIFY
          value: "false"
        - name: FMS_ORCHESTRATOR_URL
          value: "http://localhost:1234"
        # External embedding via vLLM (instead of inline sentence-transformers)
        - name: VLLM_EMBEDDING_URL
          value: "http://granite-embedding-predictor.bench.svc.cluster.local:80/v1"
        - name: EMBEDDING_PROVIDER
          value: "vllm-embedding"
        - name: EMBEDDING_MODEL
          value: "granite-embedding-external"
        - name: EMBEDDING_PROVIDER_MODEL_ID
          value: "granite-embedding"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.llamastack.svc.cluster.local:4318"
        - name: OTEL_SERVICE_NAME
          value: "llamastack"
        - name: POSTGRES_HOST
          value: "postgres.llamastack.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
      name: llama-stack
      port: 8321
    distribution:
      image: quay.io/rhoai/odh-llama-stack-core-rhel9:rhoai-3.2
    storage:
      size: 20Gi
      mountPath: /opt/app-root/src/.llama/distributions/rh
