# Tempo Monolithic instance for storing and visualizing LlamaStack traces
# Prerequisites: 
#   1. Install Red Hat Tempo Operator from OperatorHub
#   2. The operator creates the openshift-tempo-operator namespace
#
# Deploy with: oc apply -f tempo-monolithic.yaml
#
# Access Jaeger UI:
#   oc port-forward pod/tempo-tracing-0 16686:16686 -n openshift-tempo-operator
#   Then open: http://localhost:16686
#
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: tracing
  namespace: openshift-tempo-operator
spec:
  ingestion:
    otlp:
      grpc:
        enabled: true   # Collector sends to Tempo on port 4317 (gRPC)
      http:
        enabled: true   # Also accepts HTTP on port 4318 (not used in our setup)
  multitenancy:
    enabled: false
  jaegerui:
    enabled: true
    route:
      enabled: false
  # Query frontend serves Jaeger UI - needs larger message limits for big traces
  queryFrontend:
    extraConfig:
      server:
        grpc_server_max_recv_msg_size: 20971520   # 20MB
        grpc_server_max_send_msg_size: 20971520   # 20MB
  storage:
    traces:
      backend: memory   # For testing. Use S3/GCS for production.

