apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: benchmark-mcp-custom-
  namespace: tekton-llamastack
spec:
  pipelineRef:
    name: responses-mcp-benchmark
  taskRunTemplate:
    serviceAccountName: tekton-deployer
  params:
    - name: NAMESPACE
      value: "llamastack-bench"
    - name: DISTRIBUTION_NAME
      value: "llamastack-benchmark"
    - name: MODEL_NAME
      value: "llama-32-3b-instruct"
    - name: MCP_SERVER_NAME
      value: "sdg-docs-mcp-server"
    - name: USERS
      value: "10"
    - name: SPAWN_RATE
      value: "2"
    - name: RUN_TIME_SECONDS
      value: "60"
    - name: MODEL
      value: "vllm-inference/llama-32-3b-instruct"
    - name: PROMPT
      value: "What is Kubernetes?"
    - name: LOAD_SHAPE
      value: "custom"
    - name: CUSTOM_STAGES
      value: '[{"duration":30,"users":5,"spawn_rate":1},{"duration":90,"users":15,"spawn_rate":3},{"duration":150,"users":5,"spawn_rate":3}]'
    - name: ENABLE_MLFLOW
      value: "true"
    - name: MLFLOW_EXPERIMENT
      value: "llamastack-tekton-pipeline"
