apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: benchmark-mcp-spike-
  namespace: tekton-llamastack
spec:
  pipelineRef:
    name: responses-mcp-benchmark
  taskRunTemplate:
    serviceAccountName: tekton-deployer
  params:
    - name: NAMESPACE
      value: "llamastack-bench"
    - name: DISTRIBUTION_NAME
      value: "llamastack-benchmark"
    - name: MODEL_NAME
      value: "llama-32-3b-instruct"
    - name: MCP_SERVER_NAME
      value: "sdg-docs-mcp-server"
    - name: USERS
      value: "10"
    - name: SPAWN_RATE
      value: "2"
    - name: RUN_TIME_SECONDS
      value: "60"
    - name: MODEL
      value: "vllm-inference/llama-32-3b-instruct"
    - name: PROMPT
      value: "What is Kubernetes?"
    - name: LOAD_SHAPE
      value: "spike"
    - name: EXTRA_ENV
      value: |
        SPIKE_BASELINE_USERS=3
        SPIKE_PEAK_USERS=15
        SPIKE_BASELINE_DURATION=15
        SPIKE_RAMP_DURATION=10
        SPIKE_HOLD_DURATION=30
        SPIKE_COOLDOWN_DURATION=15
    - name: ENABLE_MLFLOW
      value: "true"
    - name: MLFLOW_EXPERIMENT
      value: "llamastack-tekton-pipeline"
