apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: llamastack-benchmark-
  namespace: tekton-llamastack
spec:
  pipelineRef:
    name: llamastack-benchmark
  taskRunTemplate:
    serviceAccountName: tekton-deployer
  params:
    # Namespace for vLLM, PostgreSQL, MCP server, LlamaStack (created if doesn't exist)
    - name: NAMESPACE
      value: "llamastack-bench"
    # LlamaStack
    - name: DISTRIBUTION_NAME
      value: "llamastack-benchmark"
    # vLLM - deploy in same namespace
    - name: SKIP_VLLM_DEPLOY
      value: "false"
    - name: MODEL_NAME
      value: "llama-32-3b-instruct"
    # MCP server - deploy in same namespace
    - name: SKIP_MCP_DEPLOY
      value: "false"
    - name: MCP_SERVER_NAME
      value: "sdg-docs-mcp-server"
    # Test configuration
    - name: USERS
      value: "5"
    - name: SPAWN_RATE
      value: "1"
    - name: RUN_TIME_SECONDS
      value: "60"
    - name: MODEL
      value: "vllm-inference/llama-32-3b-instruct"
    - name: PROMPT
      value: "What is Kubernetes?"
    # MLflow
    - name: ENABLE_MLFLOW
      value: "true"
    - name: MLFLOW_EXPERIMENT
      value: "llamastack-tekton-pipeline"
    # Cleanup - delete ALL deployed resources after test
    - name: SKIP_CLEANUP
      value: "false"
    - name: CLEANUP_VLLM
      value: "true"
    - name: CLEANUP_MCP
      value: "true"
    - name: DELETE_NAMESPACE
      value: "false"