apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: llamastack-benchmark
  namespace: tekton-llamastack
spec:
  description: |
    End-to-end LlamaStack benchmark pipeline.
    Deploys vLLM, MCP server, PostgreSQL, and LlamaStack, runs Locust tests, then cleans up.
  params:
    # Namespace (must already exist)
    - name: NAMESPACE
      description: Namespace for deployment (must already exist)
      type: string
      default: "llamastack-bench"
    - name: DISTRIBUTION_NAME
      description: LlamaStackDistribution name
      type: string
      default: "llamastack-benchmark"
    
    # vLLM params
    - name: MODEL_NAME
      description: vLLM model/InferenceService name
      type: string
      default: "llama-32-3b-instruct"
    - name: SKIP_VLLM_DEPLOY
      description: Skip vLLM deployment (assumes already running)
      type: string
      default: "false"
    # MCP server params
    - name: MCP_SERVER_NAME
      description: MCP server deployment name
      type: string
      default: "sdg-docs-mcp-server"
    - name: SKIP_MCP_DEPLOY
      description: Skip MCP server deployment
      type: string
      default: "false"
    
    # Test params
    - name: USERS
      description: Number of concurrent users
      type: string
      default: "10"
    - name: SPAWN_RATE
      description: Users per second
      type: string
      default: "1"
    - name: RUN_TIME_SECONDS
      description: Test duration
      type: string
      default: "60"
    - name: MODEL
      description: Model name (provider/model format)
      type: string
      default: "vllm-inference/llama-32-3b-instruct"
    - name: PROMPT
      description: Test prompt
      type: string
      default: "What is Kubernetes?"
    
    # MLflow params
    - name: ENABLE_MLFLOW
      description: Enable MLflow logging (true/false)
      type: string
      default: "false"
    - name: MLFLOW_URL
      description: MLflow tracking server URL (optional)
      type: string
      default: ""
    - name: MLFLOW_EXPERIMENT
      description: MLflow experiment name
      type: string
      default: "llamastack-benchmarks"
    
    # Control params
    - name: SKIP_CLEANUP
      description: Skip cleanup for debugging
      type: string
      default: "false"
    - name: CLEANUP_VLLM
      description: Also cleanup vLLM after test
      type: string
      default: "false"
    - name: CLEANUP_MCP
      description: Also cleanup MCP server after test
      type: string
      default: "false"
    - name: DELETE_NAMESPACE
      description: Delete entire namespace after test
      type: string
      default: "false"
  tasks:
    # Stage 1: Deploy vLLM (can run in parallel with MCP and PostgreSQL)
    - name: deploy-vllm
      taskRef:
        name: deploy-vllm
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: MODEL_NAME
          value: $(params.MODEL_NAME)
        - name: SKIP_DEPLOY
          value: $(params.SKIP_VLLM_DEPLOY)

    # Stage 1: Deploy MCP server (parallel with vLLM and PostgreSQL)
    - name: deploy-mcp-server
      taskRef:
        name: deploy-mcp-server
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: MCP_SERVER_NAME
          value: $(params.MCP_SERVER_NAME)
        - name: SKIP_DEPLOY
          value: $(params.SKIP_MCP_DEPLOY)

    # Stage 1: Deploy PostgreSQL (parallel with vLLM and MCP)
    - name: deploy-postgres
      taskRef:
        name: deploy-postgres
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)

    # Stage 2: Deploy LlamaStack (after all dependencies)
    - name: deploy-llamastack
      taskRef:
        name: deploy-llamastack
      runAfter:
        - deploy-vllm
        - deploy-mcp-server
        - deploy-postgres
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: DISTRIBUTION_NAME
          value: $(params.DISTRIBUTION_NAME)
        - name: VLLM_NAMESPACE
          value: $(params.NAMESPACE)
    # Stage 3: Run Locust test (after LlamaStack)
    - name: run-locust
      taskRef:
        name: run-locust
      runAfter:
        - deploy-llamastack
      params:
        - name: HOST
          value: "http://$(params.DISTRIBUTION_NAME)-service.$(params.NAMESPACE).svc.cluster.local:8321"
        - name: USERS
          value: $(params.USERS)
        - name: SPAWN_RATE
          value: $(params.SPAWN_RATE)
        - name: RUN_TIME_SECONDS
          value: $(params.RUN_TIME_SECONDS)
        - name: MCP_SERVER
          value: "http://$(params.MCP_SERVER_NAME).$(params.NAMESPACE).svc.cluster.local:8000/sse"
        - name: MODEL
          value: $(params.MODEL)
        - name: PROMPT
          value: $(params.PROMPT)
        - name: ENABLE_MLFLOW
          value: $(params.ENABLE_MLFLOW)
        - name: MLFLOW_URL
          value: $(params.MLFLOW_URL)
        - name: MLFLOW_EXPERIMENT
          value: $(params.MLFLOW_EXPERIMENT)

    # Stage 4: Cleanup (after test, always runs)
    - name: cleanup
      taskRef:
        name: cleanup
      runAfter:
        - run-locust
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: DISTRIBUTION_NAME
          value: $(params.DISTRIBUTION_NAME)
        - name: MODEL_NAME
          value: $(params.MODEL_NAME)
        - name: MCP_SERVER_NAME
          value: $(params.MCP_SERVER_NAME)
        - name: SKIP_CLEANUP
          value: $(params.SKIP_CLEANUP)
        - name: CLEANUP_VLLM
          value: $(params.CLEANUP_VLLM)
        - name: CLEANUP_MCP
          value: $(params.CLEANUP_MCP)
        - name: DELETE_NAMESPACE
          value: $(params.DELETE_NAMESPACE)