apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: responses-simple-benchmark
  namespace: tekton-llamastack
spec:
  description: |
    Benchmark LlamaStack Responses API without MCP tools.
    Deploys vLLM, PostgreSQL, OTel, LlamaStack, runs Locust test, logs to MLflow, cleans up.
  params:
    - name: NAMESPACE
      type: string
      default: "llamastack-bench"
    - name: DISTRIBUTION_NAME
      type: string
      default: "llamastack-benchmark"
    - name: MODEL_NAME
      type: string
      default: "llama-32-3b-instruct"
    - name: USERS
      type: string
      default: "10"
    - name: SPAWN_RATE
      type: string
      default: "1"
    - name: RUN_TIME_SECONDS
      type: string
      default: "60"
    - name: MODEL
      type: string
      default: "vllm-inference/llama-32-3b-instruct"
    - name: PROMPT
      type: string
      default: "What is the capital of France?"
    - name: LOAD_SHAPE
      type: string
      default: "steady"
    - name: CUSTOM_STAGES
      type: string
      default: "[]"
    - name: EXTRA_ENV
      type: string
      default: ""
    - name: HPA_POST_TEST_SECONDS
      type: string
      default: "30"
    - name: ENABLE_MLFLOW
      type: string
      default: "false"
    - name: MLFLOW_EXPERIMENT
      type: string
      default: "llamastack-benchmarks"
    - name: MLFLOW_RUN_NAME_PREFIX
      type: string
      default: "tekton"
    - name: TEMPO_ENDPOINT
      type: string
      default: "http://tempo-tracing.openshift-tempo-operator.svc.cluster.local:3200"
    - name: SKIP_CLEANUP
      type: string
      default: "false"
  workspaces:
    - name: results
  tasks:
    # Stage 1: Parallel deployments + configmap generation
    - name: generate-configmap
      taskRef:
        name: generate-configmap

    - name: deploy-vllm
      taskRef:
        name: deploy-vllm
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: MODEL_NAME
          value: $(params.MODEL_NAME)

    - name: deploy-postgres
      taskRef:
        name: deploy-postgres
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)

    - name: deploy-tracing
      taskRef:
        name: deploy-tracing
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)

    # Stage 2: Deploy LlamaStack
    - name: deploy-llamastack
      taskRef:
        name: deploy-llamastack
      runAfter:
        - deploy-vllm
        - deploy-postgres
        - deploy-tracing
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: DISTRIBUTION_NAME
          value: $(params.DISTRIBUTION_NAME)
        - name: VLLM_NAMESPACE
          value: $(params.NAMESPACE)

    # Stage 3: Run Locust test
    - name: run-locust
      taskRef:
        name: run-locust
      runAfter:
        - deploy-llamastack
        - generate-configmap
      workspaces:
        - name: results
          workspace: results
      params:
        - name: HOST
          value: "http://$(params.DISTRIBUTION_NAME)-service.$(params.NAMESPACE).svc.cluster.local:8321"
        - name: USER_CLASS
          value: "ResponsesSimpleUser"
        - name: USERS
          value: $(params.USERS)
        - name: SPAWN_RATE
          value: $(params.SPAWN_RATE)
        - name: RUN_TIME_SECONDS
          value: $(params.RUN_TIME_SECONDS)
        - name: MODEL
          value: $(params.MODEL)
        - name: PROMPT
          value: $(params.PROMPT)
        - name: LOAD_SHAPE
          value: $(params.LOAD_SHAPE)
        - name: CUSTOM_STAGES
          value: $(params.CUSTOM_STAGES)
        - name: EXTRA_ENV
          value: $(params.EXTRA_ENV)
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: DISTRIBUTION_NAME
          value: $(params.DISTRIBUTION_NAME)
        - name: HPA_POST_TEST_SECONDS
          value: $(params.HPA_POST_TEST_SECONDS)

    # Stage 4: Log to MLflow (conditional)
    - name: log-mlflow
      taskRef:
        name: log-mlflow
      runAfter:
        - run-locust
      when:
        - input: $(params.ENABLE_MLFLOW)
          operator: in
          values: ["true"]
      workspaces:
        - name: results
          workspace: results
      params:
        - name: MLFLOW_EXPERIMENT
          value: $(params.MLFLOW_EXPERIMENT)
        - name: MLFLOW_RUN_NAME_PREFIX
          value: $(params.MLFLOW_RUN_NAME_PREFIX)
        - name: TEMPO_ENDPOINT
          value: $(params.TEMPO_ENDPOINT)
        - name: USER_CLASS
          value: "ResponsesSimpleUser"
        - name: USERS
          value: $(params.USERS)
        - name: SPAWN_RATE
          value: $(params.SPAWN_RATE)
        - name: RUN_TIME_SECONDS
          value: $(params.RUN_TIME_SECONDS)
        - name: MODEL
          value: $(params.MODEL)
        - name: PROMPT
          value: $(params.PROMPT)
        - name: LOAD_SHAPE
          value: $(params.LOAD_SHAPE)
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: DISTRIBUTION_NAME
          value: $(params.DISTRIBUTION_NAME)
        - name: EXTRA_ENV
          value: $(params.EXTRA_ENV)
        - name: CUSTOM_STAGES
          value: $(params.CUSTOM_STAGES)

    # Stage 5: Cleanup
    - name: cleanup
      taskRef:
        name: cleanup
      runAfter:
        - log-mlflow
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: DISTRIBUTION_NAME
          value: $(params.DISTRIBUTION_NAME)
        - name: MODEL_NAME
          value: $(params.MODEL_NAME)
        - name: SKIP_CLEANUP
          value: $(params.SKIP_CLEANUP)
        - name: CLEANUP_VLLM
          value: "true"
        - name: CLEANUP_MCP
          value: "false"
