apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: responses-mcp-benchmark
  namespace: tekton-llamastack
spec:
  description: |
    Benchmark LlamaStack Responses API with MCP tool calling.
    Deploys vLLM, PostgreSQL, MCP server, LlamaStack, runs Locust test, then cleans up.
  params:
    - name: NAMESPACE
      description: Namespace for deployment
      type: string
      default: "llamastack-bench"
    - name: DISTRIBUTION_NAME
      description: LlamaStackDistribution name
      type: string
      default: "llamastack-benchmark"
    - name: MODEL_NAME
      description: vLLM model/InferenceService name
      type: string
      default: "llama-32-3b-instruct"
    - name: MCP_SERVER_NAME
      description: MCP server deployment name
      type: string
      default: "sdg-docs-mcp-server"
    # Test params
    - name: USERS
      description: Number of concurrent users
      type: string
      default: "10"
    - name: SPAWN_RATE
      description: Users per second
      type: string
      default: "1"
    - name: RUN_TIME_SECONDS
      description: Test duration
      type: string
      default: "60"
    - name: MODEL
      description: Model name (provider/model format)
      type: string
      default: "vllm-inference/llama-32-3b-instruct"
    - name: PROMPT
      description: Test prompt
      type: string
      default: "What is Kubernetes?"
    - name: LOAD_SHAPE
      description: "Load shape: steady | spike | realistic | custom"
      type: string
      default: "steady"
    - name: CUSTOM_STAGES
      description: JSON array of stages for custom load shape
      type: string
      default: "[]"
    - name: EXTRA_ENV
      description: "Additional env vars for shapes (KEY=VALUE per line)"
      type: string
      default: ""
    # MLflow params
    - name: ENABLE_MLFLOW
      description: Enable MLflow logging (true/false)
      type: string
      default: "false"
    - name: MLFLOW_URL
      description: MLflow tracking server URL (optional)
      type: string
      default: ""
    - name: MLFLOW_EXPERIMENT
      description: MLflow experiment name
      type: string
      default: "llamastack-benchmarks"
    # Control
    - name: SKIP_CLEANUP
      description: Skip cleanup for debugging
      type: string
      default: "false"
  tasks:
    # Stage 1: Deploy vLLM, PostgreSQL, MCP server in parallel
    - name: deploy-vllm
      taskRef:
        name: deploy-vllm
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: MODEL_NAME
          value: $(params.MODEL_NAME)

    - name: deploy-postgres
      taskRef:
        name: deploy-postgres
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)

    - name: deploy-mcp-server
      taskRef:
        name: deploy-mcp-server
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: MCP_SERVER_NAME
          value: $(params.MCP_SERVER_NAME)

    # Stage 2: Deploy LlamaStack after all dependencies
    - name: deploy-llamastack
      taskRef:
        name: deploy-llamastack
      runAfter:
        - deploy-vllm
        - deploy-postgres
        - deploy-mcp-server
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: DISTRIBUTION_NAME
          value: $(params.DISTRIBUTION_NAME)
        - name: VLLM_NAMESPACE
          value: $(params.NAMESPACE)

    # Stage 3: Run Locust test
    - name: run-locust
      taskRef:
        name: run-locust
      runAfter:
        - deploy-llamastack
      params:
        - name: HOST
          value: "http://$(params.DISTRIBUTION_NAME)-service.$(params.NAMESPACE).svc.cluster.local:8321"
        - name: USER_CLASS
          value: "ResponsesMCPUser"
        - name: USERS
          value: $(params.USERS)
        - name: SPAWN_RATE
          value: $(params.SPAWN_RATE)
        - name: RUN_TIME_SECONDS
          value: $(params.RUN_TIME_SECONDS)
        - name: MCP_SERVER
          value: "http://$(params.MCP_SERVER_NAME).$(params.NAMESPACE).svc.cluster.local:8000/sse"
        - name: MODEL
          value: $(params.MODEL)
        - name: PROMPT
          value: $(params.PROMPT)
        - name: LOAD_SHAPE
          value: $(params.LOAD_SHAPE)
        - name: CUSTOM_STAGES
          value: $(params.CUSTOM_STAGES)
        - name: EXTRA_ENV
          value: $(params.EXTRA_ENV)
        - name: ENABLE_MLFLOW
          value: $(params.ENABLE_MLFLOW)
        - name: MLFLOW_URL
          value: $(params.MLFLOW_URL)
        - name: MLFLOW_EXPERIMENT
          value: $(params.MLFLOW_EXPERIMENT)

    # Stage 4: Cleanup
    - name: cleanup
      taskRef:
        name: cleanup
      runAfter:
        - run-locust
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: DISTRIBUTION_NAME
          value: $(params.DISTRIBUTION_NAME)
        - name: MODEL_NAME
          value: $(params.MODEL_NAME)
        - name: MCP_SERVER_NAME
          value: $(params.MCP_SERVER_NAME)
        - name: SKIP_CLEANUP
          value: $(params.SKIP_CLEANUP)
        - name: CLEANUP_VLLM
          value: "true"
        - name: CLEANUP_MCP
          value: "true"
