apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: vllm-direct-benchmark
  namespace: tekton-llamastack
spec:
  description: |
    Benchmark vLLM directly (no LlamaStack).
    Deploys vLLM, runs Locust ChatCompletions test, logs to MLflow, cleans up.
  params:
    - name: NAMESPACE
      type: string
      default: "llamastack-bench"
    - name: MODEL_NAME
      type: string
      default: "llama-32-3b-instruct"
    - name: USERS
      type: string
      default: "10"
    - name: SPAWN_RATE
      type: string
      default: "1"
    - name: RUN_TIME_SECONDS
      type: string
      default: "60"
    - name: MODEL
      type: string
      default: "llama-32-3b-instruct"
    - name: PROMPT
      type: string
      default: "What is the capital of France?"
    - name: LOAD_SHAPE
      type: string
      default: "steady"
    - name: CUSTOM_STAGES
      type: string
      default: "[]"
    - name: EXTRA_ENV
      type: string
      default: ""
    - name: HPA_POST_TEST_SECONDS
      type: string
      default: "30"
    - name: ENABLE_MLFLOW
      type: string
      default: "false"
    - name: MLFLOW_EXPERIMENT
      type: string
      default: "llamastack-benchmarks"
    - name: MLFLOW_RUN_NAME_PREFIX
      type: string
      default: "tekton"
    - name: SKIP_CLEANUP
      type: string
      default: "false"
  workspaces:
    - name: results
  tasks:
    - name: generate-configmap
      taskRef:
        name: generate-configmap

    - name: deploy-vllm
      taskRef:
        name: deploy-vllm
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: MODEL_NAME
          value: $(params.MODEL_NAME)

    - name: run-locust
      taskRef:
        name: run-locust
      runAfter:
        - deploy-vllm
        - generate-configmap
      workspaces:
        - name: results
          workspace: results
      params:
        - name: HOST
          value: "http://$(params.MODEL_NAME)-predictor.$(params.NAMESPACE).svc.cluster.local:80"
        - name: USER_CLASS
          value: "ChatCompletionsUser"
        - name: USERS
          value: $(params.USERS)
        - name: SPAWN_RATE
          value: $(params.SPAWN_RATE)
        - name: RUN_TIME_SECONDS
          value: $(params.RUN_TIME_SECONDS)
        - name: MODEL
          value: $(params.MODEL)
        - name: PROMPT
          value: $(params.PROMPT)
        - name: LOAD_SHAPE
          value: $(params.LOAD_SHAPE)
        - name: CUSTOM_STAGES
          value: $(params.CUSTOM_STAGES)
        - name: EXTRA_ENV
          value: $(params.EXTRA_ENV)
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: DISTRIBUTION_NAME
          value: "none"
        - name: HPA_POST_TEST_SECONDS
          value: $(params.HPA_POST_TEST_SECONDS)

    - name: log-mlflow
      taskRef:
        name: log-mlflow
      runAfter:
        - run-locust
      when:
        - input: $(params.ENABLE_MLFLOW)
          operator: in
          values: ["true"]
      workspaces:
        - name: results
          workspace: results
      params:
        - name: MLFLOW_EXPERIMENT
          value: $(params.MLFLOW_EXPERIMENT)
        - name: MLFLOW_RUN_NAME_PREFIX
          value: $(params.MLFLOW_RUN_NAME_PREFIX)
        - name: USER_CLASS
          value: "ChatCompletionsUser"
        - name: USERS
          value: $(params.USERS)
        - name: SPAWN_RATE
          value: $(params.SPAWN_RATE)
        - name: RUN_TIME_SECONDS
          value: $(params.RUN_TIME_SECONDS)
        - name: MODEL
          value: $(params.MODEL)
        - name: PROMPT
          value: $(params.PROMPT)
        - name: LOAD_SHAPE
          value: $(params.LOAD_SHAPE)
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: EXTRA_ENV
          value: $(params.EXTRA_ENV)
        - name: CUSTOM_STAGES
          value: $(params.CUSTOM_STAGES)

    - name: cleanup
      taskRef:
        name: cleanup
      runAfter:
        - log-mlflow
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: MODEL_NAME
          value: $(params.MODEL_NAME)
        - name: SKIP_CLEANUP
          value: $(params.SKIP_CLEANUP)
        - name: CLEANUP_VLLM
          value: "true"
        - name: CLEANUP_MCP
          value: "false"
